server:
  port: 8761    #DEFAULT_URL = "http://localhost:8761" #
spring:
  application:
    name: eureka-server
eureka:
  #client:
    #service-url:     #DEFAULT_ZONE = "defaultZone";
      #defaultZone: http://localhost:8888